# Generated by Django 5.2.5 on 2026-08-27 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='allow_reactions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='story',
            name='decorations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='story',
            name='media_type',
            field=models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], max_length=10),
        ),
        migrations.CreateModel(
            name='StoryReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction', models.CharField(choices=[('heart', '❤️'), ('laugh', '😂'), ('love', '😍'), ('wow', '😮'), ('sad', '😢'), ('fire', '🔥')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='stories.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('story', 'user'), name='unique_story_user_reaction')],
            },
        ),
    ]
