# Generated by Django 5.2.5 on 2026-08-27 23:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['chat_type', 'updated_at'], name='chats_chat_chat_ty_631beb_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['updated_at'], name='chats_chat_updated_b952c1_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmember',
            index=models.Index(fields=['user', 'last_read_at'], name='chats_chatm_user_id_76fbfc_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmember',
            index=models.Index(fields=['chat', 'joined_at'], name='chats_chatm_chat_id_f3c5c3_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'created_at'], name='chats_messa_chat_id_a8ed7c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'is_deleted', 'created_at'], name='chats_messa_chat_id_606c04_idx'),
        ),
    ]
