# Generated by Django 5.2.5 on 2026-08-27 23:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_chats_chat_chat_ty_631beb_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chat',
            name='chats_chat_updated_b952c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatmember',
            name='chats_chatm_chat_id_f3c5c3_idx',
        ),
        migrations.AddField(
            model_name='chat',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('private', 'Личный чат'), ('group', 'Группа'), ('channel', 'Сообщество')], default='private', max_length=20),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['is_public', 'chat_type'], name='chats_chat_is_publ_c2c283_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmember',
            index=models.Index(fields=['chat', 'user'], name='chats_chatm_chat_id_e4095c_idx'),
        ),
    ]
