# Generated by Django 5.2.5 on 2026-08-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_options_post_is_pinned_post_post_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_accepted',
            field=models.BooleanField(default=True),
        ),
    ]
